### ISSUE TITLE
Set primary key of `checkers` table to be uuid instead of checker name

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/checkfirst#230]
### Overview, Problem Description, Summary, or Abstract
Currently, the `checkers` table has a primary key of `id`. However, this `id` represents the name of the checker, as such, an admin user will not be able to rename their checker if they wanted to.

### Solution
Modify the primary key `id` to represent a random UUID and create a new `name` field to represent the checker name. Additionally, set the URL of the checker to use the new `id` instead of the `name` field so that we prevent broken links from happening whenever the checker name is modified.

**Comment by LoneRifle** [comment]
As discussed, 
- we will repurpose `id` - instead of a human readable kebab-case identifier, this will be a UUID. 
- we have `title` already, so `name` is not needed. 
- existing checkers can retain their legacy human readable identifiers, to ease the migration.
