### ISSUE TITLE
Incorporate link to guide when user is editing their checker

### ISSUE THREAD

**Issue by lisa-kwok** [opengovsg/checkfirst#262]
**Is your feature request related to a problem? Please describe.**
Link to guide is currently only available on the dashboard page. 
As users will likely need help and reference to guide while building their checker, the guide should be easily accessible on the edit checker page.

**Describe the solution you'd like**
A question mark icon at the top bar next to iframe icon. 
<img width="566" alt="Screenshot 2021-03-22 at 1 37 53 PM" src="https://user-images.githubusercontent.com/23736580/111945148-1b62d200-8b14-11eb-8932-d01c31343523.png">

**Comment by NatMaeTan** [comment]
Refer to updated floating help icon UI [here](https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=1530%3A0)
