### ISSUE TITLE
Dropdown option

### ISSUE THREAD

**Issue by lisa-kwok** [opengovsg/checkfirst#264]
**Is your feature request related to a problem? Please describe.**
When there are multiple of more than 10 items to select from, listing every single option on radio button is not a good experience (since the user has to scroll a long page of selection) 

**Describe the solution you'd like**
Dropdown option. 
<img width="708" alt="Screenshot 2021-03-22 at 1 49 54 PM" src="https://user-images.githubusercontent.com/23736580/111945906-7fd26100-8b15-11eb-97ed-2ccf8a8f5151.png">

**Comment by LoneRifle** [comment]
Initial implementation done in #276

**Comment by lisa-kwok** [comment]
released in v.1.10
