### ISSUE TITLE
Make button unclickable when it can't be changed

### ISSUE THREAD

**Issue by lisa-kwok** [opengovsg/checkfirst#265]
See screenshot below 

<img width="469" alt="Screenshot 2021-03-22 at 1 52 00 PM" src="https://user-images.githubusercontent.com/23736580/111946149-ea839c80-8b15-11eb-86d7-783e0d59d534.png">

**Comment by prestonlimlianjie** [comment]
I accidentally created a duplicate issue https://github.com/opengovsg/checkfirst/issues/330. Closing this one since I've tied the fix PR to the other issue.
