### ISSUE TITLE
collaborators on checkers

### ISSUE THREAD

**Issue by lisa-kwok** [opengovsg/checkfirst#266]
**Is your feature request related to a problem? Please describe.**
Checkers are likely to be maintained by multiple users just like forms. 

Implementation:
1. Checker owner will be the admin
2. Other users must be added by the checker owner
3. Optional: should we allow changing of owners? this means checker transfer. 

Additional considerations: how to handle concurrency issues?

**Comment by prestonlimlianjie** [comment]
There are still other questions that we need to address before building out the feature:
- If we don't allow changing of owners - what happens when a checker admin user leaves the organization?
- Can non-admin users of a checker delete the checker?
- Can non-admin users of a checker leave the checker?
- Can admin users of a checker delete users from the checker?

**Comment by NatMaeTan** [comment]
Looking at the current flow of formsg, 

1. Creator of checker is the owner
2. Checker ownership can be transferred to others
3. Both owner and collaborators can add new or delete existing collaborators
5. Both owner and collaborators can change the status of other collaborators from Editor to read-only (Not applicable to CF)
4. Collaborators can deactivate the checker
5. Collaborators cannot delete a checker

**Comment by NatMaeTan** [comment]
[Figma UI](https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=2436%3A11230)

**Comment by lisa-kwok** [comment]
To sum it up:
1. Creator of checker is the owner
2. Checker ownership can be transferred to others (done manually on DB, upon request by a collaborator - to figure out pre written script to run)
3. Both owner and collaborators can add new or delete existing collaborators (collaborators **cannot** delete owner) 
4. Collaborators can deactivate the checker
5. Collaborators **cannot** delete a checker

**Comment by NatMaeTan** [comment]
Would the request to transfer ownership be built into the UI, or do users have to email in?
