### ISSUE TITLE
Form revert back to default when user navigate away from checkfirst window 

### ISSUE THREAD

**Issue by lisa-kwok** [opengovsg/checkfirst#288]
**Describe the bug**
When creating the fifth question, it gets reverted into the default question when the user navigates to a separate window other than checkfirst. 

**To Reproduce**
1. Create fifth question and the option
2. Click away from checkfirst window to another tab or chrome or another app

**Expected behavior**
The form should not be reverted to default when user navigates aware

**Comment by LoneRifle** [comment]
Fixed by #289
