### ISSUE TITLE
Add a preview-publish flow

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/checkfirst#300]
## Is your feature request related to a problem? Please describe.
Currently, when the admin user modifies and saves a checker, the checker is immediately published. We would like to add a new flow that allows the admin user to 1) preview the checker and then 2) explicitly publish the checker when they are ready to do so.

## Describe the solution you'd like
Design done by Natalie: https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=1417%3A15883

#### Database/Model layer
- Create a new `PublishedCheckers` table that contains the same basic fields as the `Checkers` table and is associated to a Checker
- There will be a 1-to-many relationship between Checkers and PublishedCheckers

#### API routes layer
```
// New endpoints
  api.get('/c/:id', checker.getPublished)
  api.post('/c/drafts/:id/publish', checker.publish)
  api.post('/c/drafts', checker.post)
  api.get('/c/drafts', checker.list)
  api.get('/c/drafts/:id', checker.get)
  api.put('/c/drafts/:id', checker.put)
  api.delete('/c/drafts/:id', checker.delete)
```

#### Services layer
- Create new `checker.getPublished()` method to return the latest version of the published checker
- Create new `checker.publish()` method to publish existing checker draft

#### Migrations
- Create the relevant migrations for the database

**Comment by lisa-kwok** [comment]
appending the working doc for this thread[ here](https://docs.google.com/document/d/1rpqjfWTNcb_Eqv_a8mRl4hrKphIcItr7rzLabcYf3Ws/edit#heading=h.p0igmd5ylcux)
