### ISSUE TITLE
Implement release procedure

### ISSUE THREAD

**Issue by lisa-kwok** [opengovsg/checkfirst#303]
Things to include in the release procedure:
1. Release checklist - list of things to go through (front end/backend checks before each releases) 
2. Changelog.md
3. End to End tests (will override release checklist if this is present)

**Comment by prestonlimlianjie** [comment]
Release procedure:
https://docs.google.com/document/d/1XqRxgKBzRPkH0iS3Gy4RAq5E4T1z-Fz1qXpsn2zWIGQ/edit#
