### ISSUE TITLE
Add database test in pingdom

### ISSUE THREAD

**Issue by barnettx** [opengovsg/checkfirst#316]
## Problem
For `1.1.0` release, our database wasn't working yet there was no notification from pingdom. This is because our pingdom endpoint immediately returns a response.

## Solution
Add a trivial DB statement such as `SELECT 1+1 AS RESULT` in pingdom endpoint to ensure DB is online.

**Comment by lamkeewei** [comment]
For each lambda invocation, we run `sequelize.authenticate` again. Reference [here](https://github.com/opengovsg/checkfirst/blob/8077266323a76330ae90c161da2d0bc1af6f00bd/src/server/bootstrap/index.ts#L165). This should be sufficient to catch DB failures.
