### ISSUE TITLE
Add hyperlink to published checker in successful publish toast 

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/checkfirst#326]
This is the high fidelity design:
<img width="601" alt="Screenshot 2021-04-06 at 1 44 42 PM" src="https://user-images.githubusercontent.com/19917616/113664395-42a5cb80-96de-11eb-8b2a-8f015c9932e6.png">

However, the chakra-ui `toast` component does not allow hyperlinks in the toast description by default. We could circumvent this by creating our own custom `toast` component: https://chakra-ui.com/docs/feedback/toast#custom-component

**Comment by orbitalsqwib** [comment]
> Do not include links in toasts
> Toasts are timed and it may be difficult for users with screenreaders to catch the link in time.

To align with the new design system, hyperlinks for toasts will not be implemented in favor of the preview function for quick referencing. Additionally, the new settings page should make it easier for users to get to their newly published checkers without having to manually copy/paste the public URL into their search bars
