### ISSUE TITLE
Hidden logic blocks

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/checkfirst#332]
### Problem
There is no preview that logic is hidden when unfocused. Issue raised by @NatMaeTan.
<img width="907" alt="Screenshot 2021-04-06 at 2 53 17 PM" src="https://user-images.githubusercontent.com/19917616/113670540-d760f700-96e7-11eb-923e-de6c4c23b831.png">
<img width="838" alt="Screenshot 2021-04-06 at 2 53 12 PM" src="https://user-images.githubusercontent.com/19917616/113670551-da5be780-96e7-11eb-82ba-3de8cb61bc4c.png">

### Fix
Add an overlay on logic blocks that are hidden when unfocused

**Comment by lamkeewei** [comment]
@NatMaeTan is there a design on how the "unfocused" state should look like for each of the logic blocks?

**Comment by NatMaeTan** [comment]
Yup, [here you go](https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=2143%3A29053)!
