### ISSUE TITLE
Long user input gets hidden from view

### ISSUE THREAD

**Issue by prestonlimlianjie** [opengovsg/checkfirst#335]
### Problem
Long formulas spill over and get hidden from view.
<img width="706" alt="Screenshot 2021-04-06 at 2 59 04 PM" src="https://user-images.githubusercontent.com/19917616/113671239-ac2ad780-96e8-11eb-844e-a76938b7eee5.png">

### Fix
Possible to stretch text area for better editing experience?

**Comment by lamkeewei** [comment]
Main blocker for this now is that `downshift` does not recognise `textarea` as a valid input element.

**Comment by orbitalsqwib** [comment]
Should be unblocked by #581.

**Comment by lamkeewei** [comment]
Done! #911
