### ISSUE TITLE
Results format on mobile

### ISSUE THREAD

**Issue by lisa-kwok** [opengovsg/checkfirst#432]
The current formatting of result is not ideal on mobile. 

<img width="334" alt="Screenshot 2021-04-26 at 2 42 50 PM" src="https://user-images.githubusercontent.com/23736580/116039732-aef06b00-a69d-11eb-98e5-06624c7e5d35.png">

Fix: [Figma here](https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=2075%3A0)

**Comment by NatMaeTan** [comment]
Quickfix:
![Frame 488](https://user-images.githubusercontent.com/63220614/116040135-350cb180-a69e-11eb-97ce-cea4fe830f95.png)

[Figma file](https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=2075%3A0)
