### ISSUE TITLE
Allow checkers to be unpublished through settings modal

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/checkfirst#466]
**Is your feature request related to a problem? Please describe.**
Once published, there is currently no way for taking a checker offline. This might be an issue if users do not want to delete their checker but just want to simply make it unavailable temporarily (before a embargo is lifted for a new policy, etc).

**Solution**
![image](https://user-images.githubusercontent.com/3666479/116513617-74383e00-a8fc-11eb-9e72-6bdd81d64bb6.png)
 
- Allow users to toggle visibility of their checker through the Settings modal (previously Embed Modal)
- Change copy for "Publish" button to "Publish Changes" to better reflect that they are publishing changes

**Comment by NatMaeTan** [comment]
Figma screens can be viewed [here](https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=2134%3A28981)

Includes 
→ Draft state
→ Published state
→ Unpublished state

This modal can be accessed from
→ Dashboard actions dropdown
<img width="500" alt="Dashboard_Dropdown" src="https://user-images.githubusercontent.com/63220614/116528294-3e9c5080-a90e-11eb-837a-59540bcdd3f2.png">

→ Nav bar cog icon
<img width="500" alt="Screenshot 2021-04-29 at 5 12 33 PM" src="https://user-images.githubusercontent.com/63220614/116528325-4a881280-a90e-11eb-9c20-d680efe67ccc.png">

→ Preview mode nav bar cog icon
<img width="500" alt="Screenshot 2021-04-29 at 5 12 37 PM" src="https://user-images.githubusercontent.com/63220614/116528342-4fe55d00-a90e-11eb-95d4-14d888ce9a84.png">

**Comment by prestonlimlianjie** [comment]
Had a discussion with @NatMaeTan about the implementation details about this feature and https://github.com/opengovsg/checkfirst/issues/467. We decided to do more research about "publishing".

Currently, the term "publish" is overloaded:
- **Definition 1:** Publishing/unpublishing in the settings modal refers to whether the checker is live or not, that is, can a public user view the checker
- **Definition 2:** Publish in the checker editor refers to merging the changes into the live checker. 

However, if the user clicks on the Publish button in the checker editor (definition 2) while the checker is set to unpublished in the settings modal, the changes are published but the checker is unpublished. This is quite confusing, so we'll take a little more time to think this through.

**Comment by lamkeewei** [comment]
Done with collaborator's flow added
