### ISSUE TITLE
Show checker status on Dashboard

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/checkfirst#467]
**Is your feature request related to a problem? Please describe.**
Our dashboard does not show the publish status of a particular checker. Users have to click into the checker to see the status of the checker.

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/3666479/116514108-23751500-a8fd-11eb-8bbc-3be3b89dcf8d.png)

- Show status in dashboard (Draft/Unpublished/Published)
- Add drop down menu for quick actions (Edit/Settings/Duplicate/Delete)

**Comment by NatMaeTan** [comment]
Figma file can be found [here](https://www.figma.com/file/qtoA63mFtCW3jGYhr8ev7y/Master?node-id=1419%3A19694)

There are 3 states: 
1. Draft – Changes have never been published before
2. Published – Changes have been published before and is still _published_
3. Unpublished – Changes have been published before but was switched to _unpublish_

**Comment by prestonlimlianjie** [comment]
Removed from milestone v1.4.0 because we need more time to think through the term "publish" - refer to https://github.com/opengovsg/checkfirst/issues/466#issuecomment-831788491

**Comment by orbitalsqwib** [comment]
Closed by #574
