### ISSUE TITLE
checker title and description cannot be edited on checkers with more than one question field

### ISSUE THREAD

**Issue by orbitalsqwib** [opengovsg/checkfirst#538]
**Describe the bug**
The checker title and description builder field cannot be focused when there is more than one question field.

**To Reproduce**
1. Create a checker
2. Add one question field
3. The title and description field should still be accessible
4. Add another question field
5. Note that you now cannot focus on the title and description field.

**Expected behavior**
The title and description field should be accessible at all times within the questions tab

**Screenshots**

https://user-images.githubusercontent.com/21305518/117925835-63d78880-b32a-11eb-86b1-3cdefba94ee0.mov

**Comment by lamkeewei** [comment]
Fixed in #539
