### ISSUE TITLE
[Design System] Toasts

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/checkfirst#547]
**Work required**
- Implement a [custom Toast component](https://chakra-ui.com/docs/feedback/toast#custom-component) that follows design system styling

Refer to [CheckFirst Design System](https://www.figma.com/file/X3oi4JnynZuJ2j6zSHDnTH/CheckFirst-Design-System) for details.

**Comment by orbitalsqwib** [comment]
> To align with the new design system, hyperlinks for toasts will not be implemented in favor of the preview function for quick referencing. Additionally, the new settings page should make it easier for users to get to their newly published checkers without having to manually copy/paste the public URL into their search bars

Updated work requirements in accordance with the change mentioned above.
