### ISSUE TITLE
Filter out dependabot commits in CHANGELOG

### ISSUE THREAD

**Issue by lamkeewei** [opengovsg/checkfirst#550]
**Is your feature request related to a problem? Please describe.**
Dependabot commits add quite abit of noise to our CHANGELOG. We should filter out these commits when generating out CHANGELOG during release so that it is easier to identify what are the key changes. 

**Describe the solution you'd like**
[Ignore commits](http://github.com/CookPete/auto-changelog#:~:text=--ignore-commit-pattern) from dependabot when generating CHANGELOG.

**Comment by aniruddha-adhikary** [comment]
@lamkeewei #777 fixes this :)

**Comment by lamkeewei** [comment]
Done!
