### ISSUE TITLE
Long numbers should not be shortened

### ISSUE THREAD

**Issue by NatMaeTan** [opengovsg/checkfirst#668]
**Is your feature request related to a problem? Please describe.**
Sometimes, long numbers get shortened with an e
<img width="1160" alt="Screenshot 2021-06-03 at 11 36 41 AM copy" src="https://user-images.githubusercontent.com/63220614/121130723-6235ad80-c861-11eb-93d9-3791a509aa53.png">

This makes it hard for users to know what the full number is, and also annoying when users are using CF for phone number use cases. 

**How to replicate**
When typing in `N1 == 61234567` and clicking out of the logic block, then clicking back in. Think it only happens in IF/ELSE logic block

**Describe the solution you'd like**
Numbers should not be shortened, full number should be displayed

**Comment by orbitalsqwib** [comment]
After taking a look into the issue, it seems to be an issue with the mathjs `node.toString()` method we use for unpacking the expression into separate fields. I believe that we might want to start looking into ways to avoid the premature parsing of conditional result fields, which has been giving us issues for a while now.
