### ISSUE TITLE
incorporate hyperlink and line break into the calculator bar

### ISSUE THREAD

**Issue by lisa-kwok** [opengovsg/checkfirst#876]
**Is your feature request related to a problem? Please describe.**
This makes it easier for users to insert links/line breaks in their results without referring to the guide.

<img width="383" alt="Screenshot 2021-07-28 at 12 00 55 PM" src="https://user-images.githubusercontent.com/23736580/127261775-d46f3e9f-733f-438e-843f-f4ef69552225.png">

**Comment by NatMaeTan** [comment]
Link icon
![link-regular-24](https://user-images.githubusercontent.com/63220614/127276818-804e28cf-7020-4545-a00b-d69945f915ed.png)
Clicking on link icon should prefill:
<img width="1000" alt="Screenshot 2021-07-28 at 2 44 38 PM" src="https://user-images.githubusercontent.com/63220614/127276628-0e5f443b-8574-4a43-a357-8d617fe43772.png">


Line break/paragraph Icon
![paragraph-regular-24](https://user-images.githubusercontent.com/63220614/127276838-b2dbaed0-ca10-4431-863e-a1b6dc265163.png)


**Shall we also add in an Icon for quotes?**

Quotes icon
![quote-alt-left-solid-24](https://user-images.githubusercontent.com/63220614/127276963-fe579155-3f7a-45dd-b7ec-08165a9a988d.png)
Clicking on quotes icon should prefill:
<img width="1000" alt="Screenshot 2021-07-28 at 2 45 05 PM" src="https://user-images.githubusercontent.com/63220614/127276727-3c605ecf-3123-4a7a-af93-b1936429ab91.png">

Calculator bar:
<img width="1000" alt="Screenshot 2021-07-28 at 2 50 09 PM" src="https://user-images.githubusercontent.com/63220614/127277186-42455508-b2a6-4cc3-979b-f4aa7824aced.png">
